config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :patient
  devise_for :doctors

  resources :patients, only: [:index, :show]
  resources :doctors, only: [:index, :show] do
    resources :appointments, only: [:new, :create, :show]
  end

  root to: "home#index"

  resources :appointments do
    collection do
      get :closed_appointments
    end

    member do
      put :close
    end

    resources :recommendations, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :recommendation

  scope :closed, -> { where(status: 'closed') }


end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, uniqueness: true

  has_many :doctors

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["doctors"]
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :category
  has_many :appointments

  validates :email, :phone, :full_name, :age, :city, presence: true
  validates :phone, uniqueness: true

  def email_required?
   false
  end

  def email_changed?
   false
  end
  def self.ransackable_attributes(auth_object = nil)
    ["age", "categor_id", "category_id", "city", "created_at", "email", "encrypted_password", "full_name", "id", "phone", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end


end

app/models/patient.rb
class Patient < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments

  validates :email, :phone, :full_name, :age, :city, presence: true
  validates :phone, uniqueness: true

  def email_required?
   false
  end

  def email_changed?
   false
  end

  def self.ransackable_attributes(auth_object = nil)
    ["age", "city", "created_at", "email", "encrypted_password", "full_name", "id", "phone", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :appointment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :full_name, :phone, :age, :city, :category_id, :password, :password_confirmation])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_patient!, only: [:new, :create]

  def index
    if doctor_signed_in?
      @appointments = current_doctor.appointments
    elsif patient_signed_in?
      @appointments = current_patient.appointments
    else
      redirect_to root_path, alert: 'Access denied.'
    end
  end


  def new
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = @doctor.appointments.new
  end

  def create
    @doctor = Doctor.find(params[:doctor_id])

    if @doctor.appointments.where(status: 'open').count >= 10
      redirect_to root_path, alert: 'Doctor has reached the limit of open appointments.'
    else
      @appointment = @doctor.appointments.new(appointment_params)
      @appointment.patient = current_patient

      if @appointment.save
        redirect_to patient_path(current_patient), notice: 'Appointment created successfully.'
      else
        render :new
      end
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
    @recommendation = @appointment.recommendation
  end

  def closed_appointments
    @appointments = current_doctor ? current_doctor.appointments.closed : current_patient.appointments.closed

  end


  def close
    @appointment = Appointment.find(params[:id])
    @appointment.update(status: 'closed')

    redirect_to patient_path(current_patient), notice: 'Appointment closed successfully.'
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :time, :problem)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @categories = Category.all
    category_id = params[:category_id]

    if category_id.present?
      @doctors = Doctor.where(category_id: category_id)
    else
      @doctors = Doctor.all
    end
  end

  def show
    @doctor = Doctor.find(params[:id])
    @appointments = @doctor.appointments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def show; end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = current_patient
    @active_appointments = current_patient.appointments.where(status: 'open')
    @closed_appointments = current_patient.appointments.where(status: 'closed')
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def new
    @appointment = Appointment.find(params[:appointment_id])
    @recommendation = Recommendation.new(appointment: @appointment)
  end

  def create
    @appointment = Appointment.find(params[:appointment_id])
    @recommendation = @appointment.build_recommendation(recommendation_params)

    if @recommendation.save
      @appointment.update(status: 'closed')

      redirect_to appointment_path(@appointment), notice: 'Recommendation was successfully created.'
    else
      render :new
    end
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/appointments/closed_appointments.html.erb
<!-- app/views/appointments/closed_appointments.html.erb -->
<h1 class="mb-4">Closed Appointments</h1>
<p class="mb-4">Total Closed Appointments: <%= @appointments.size %></p>

<ul class="list-group mb-4">
  <% @appointments.each do |appointment| %>
    <li class="list-group-item">
      <%= link_to "Appointment with #{appointment.patient.email}", appointment_path(appointment) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to Appointments", doctor_path(current_doctor), class: "btn btn-primary mb-4" %>

<hr>

<% @appointments.each do |appointment| %>
  <div class="card mb-4">
    <div class="card-body">
     <strong> <%= link_to "Appointment with #{appointment.patient.email}", appointment_path(appointment) %></strong>

      <p class="card-text"><strong>Date:</strong> <%= appointment.date %></p>
      <p class="card-text"><strong>Time:</strong> <%= appointment.time %></p>
      <p class="card-text"><strong>Problem:</strong> <%= appointment.problem %></p>
      <% if appointment.recommendation %>
        <p><strong>Recommendation:</strong> <%= appointment.recommendation.content %></p>
      <% end %>
      <p class="card-text text-danger"><strong>Status:</strong> Closed</p>
    </div>
  </div>
<% end %>

app/views/appointments/index.html.erb
<div class="container">
  <h1 class="mb-4">Your Appointments</h1>

  <ul class="list-group mb-4">
    <% @appointments.each do |appointment| %>
      <li class="list-group-item">
        <%= link_to "Appointment with: #{appointment.doctor.email}", appointment_path(appointment) %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Back to Home",  patient_path(current_patient), class: "btn btn-primary mb-4" %>

  <h2 class="mb-4">Closed Appointments: <%= @appointments.closed.size %></h2>
  <p>Total Closed Appointments: <%= @appointments.closed.size %></p>

   <div class="row">
    <% @appointments.each do |appointment| %>
      <% if appointment.status == 'closed' %>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h6 class="card-title"><strong><%= link_to "Appointment with: #{appointment.doctor.email}", appointment_path(appointment) %></strong></h6>
              <p class="card-text"><strong>Date:</strong> <%= appointment.date %></p>
              <p class="card-text"><strong>Time:</strong> <%= appointment.time %></p>
              <p class="card-text"><strong>Problem:</strong> <%= appointment.problem %></p>
              <p class="card-text text-danger"><strong>Status:</strong> Closed</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/appointments/new.html.erb
<!-- app/views/appointments/new.html.erb -->
<div class="container mt-5">
  <h2>Create New Appointment</h2>
  <%= form_with(model: [@doctor, @appointment], url: doctor_appointments_path(@doctor), class: "mt-3") do |form| %>
    <div class="mb-3">
      <%= form.label :date, class: "form-label" %>
      <%= form.date_field :date, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :time, class: "form-label" %>
      <%= form.time_field :time, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :problem, class: "form-label" %>
      <%= form.text_area :problem, class: "form-control", rows: 4 %>
    </div>

    <%= form.submit "Create Appointment", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/appointments/show.html.erb
<!-- app/views/appointments/show.html.erb -->
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h2>Appointment Details</h2>
      </div>

      <div class="card-body">
        <p><strong>Status:</strong> Closed</p>
        <p><strong>Date:</strong> <%= @appointment.date %></p>
        <p><strong>Time:</strong> <%= @appointment.time %></p><hr>
        <p><strong>Problem:</strong> <%= @appointment.problem %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h2>Recommendation</h2>
      </div>
      <div class="card-body">
        <% if @recommendation %>
          <p><strong>From Doctor:</strong> <%= @appointment.doctor.email %></p>
          <p><%= @recommendation.content %></p>
        <% else %>
          <p>No recommendation available.</p>
        <% end %>

        <%= link_to "Recommendations", new_appointment_recommendation_path(@appointment), class:"btn btn-primary type=button" if doctor_signed_in? %>
      </div>
    </div>
  </div>
</div>

<hr>
<div class="d-grid gap-2">
<%= link_to " << Back to Appointments", doctor_path(@appointment.doctor), class:"btn btn-primary type=button" %>
</div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/doctors/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <% @doctors.each do |doctor| %>
          <div class="col-md-15">
            <div class="card mt-3">
              <div class="card-body">
                <div class="card-header">
                  <h3> <%= doctor.full_name %></h3>
                 </div>
                <p><strong>Email:</strong> <%= doctor.email %></p>
                <p><strong>Phone:</strong> <%= doctor.phone %></p>
                <p><strong>City:</strong> <%= doctor.city %></p>
                <p><strong>Age:</strong> <%= doctor.age %></p>
                <p><strong>Doctor:</strong> <%= doctor.category.title %></p><hr>
                <div class="d-grid gap-2">
                  <%= link_to "View profile" ,doctor_path(doctor), class:"btn btn-primary button" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card mt-3">
        <div class="card-header">
          Categories
        </div>
        <div class="card-body">
          <ul class="list-group">
            <% @categories.each do |category| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to category.title, doctors_path(category_id: category.id), class: 'btn btn-link' %>
               <span class="badge bg-primary rounded-pill"><%= category.doctors.count %></span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/show.html.erb
<div class="profile-container">
  <h1>Doctor Profile</h1>

  <% if @doctor.present? %>
    <div class="user-info">
      <p>
        <strong>Full Name:</strong> <%= @doctor.full_name %><br>
        <strong>Email:</strong>     <%= @doctor.email %><br>
        <strong>Phone:</strong>     <%= @doctor.phone %><br>
        <strong>Age:</strong>       <%= @doctor.age %><br>
        <strong>City:</strong>      <%= @doctor.city %><br>
        <% if @doctor.category.present? %>
          <strong>Category:</strong> <%= @doctor.category.title %><br>
        <% end %>
      </p><hr>

      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "Create Appointment", new_doctor_appointment_path(@doctor), class:"btn btn-primary type=button" if patient_signed_in? %>
     </div>


      <div class="profile-actions">
        <% if doctor_signed_in? && current_doctor == @doctor %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= link_to "My Appointments", closed_appointments_appointments_path,  class:"btn btn-warning" %>
            <%= link_to 'Edit Profile', edit_doctor_registration_path, class:"btn btn-primary me-md-2 button" %>
            <%= link_to 'Log out', destroy_doctor_session_path, method: :delete, data: { turbo_method: :delete }, class:"btn btn-danger me-md-2 button"%>
          </div>
        <% end %>
      </div>
    </div>

    <% if doctor_signed_in? && current_doctor == @doctor %>
      <div class="card">
        <div class="card-header">

          <h2>Open Appointments:<%= @doctor.appointments.where(status: 'open').count %></h2>

        </div>
        <div class="card-body">
          <% @doctor.appointments.each do |appointment| %>
            <% if appointment.status == 'open' %>
              <li>
                <%= link_to "Appointment with #{appointment.patient.email}", appointment_path(appointment) %>
              </li>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

  <% else %>
    <p>User not found</p>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="px-4 pt-5 my-5 text-center border-bottom">
  <h1 class="display-4 fw-bold">Meet Our Experienced Doctors</h1>
    <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Our team of dedicated and experienced doctors is committed to providing exceptional healthcare services. With expertise in various medical specialties, our doctors prioritize patient care, ensuring personalized and compassionate treatment. Trust in the expertise of our medical professionals to guide you on your journey to optimal health.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <% unless doctor_signed_in? || patient_signed_in? %>
      <%= link_to "I am User", patient_session_path, class: "login-button type=button" %>
      <%= link_to "I am Doctor", doctor_session_path, class: "login-button type=button" %>
    <% end %>
      </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
      <div class="container px-5">
        <%= image_tag('foto_htree.jpg', alt: 'Description of the image') %>
      </div>
    </div>
  </div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/patients/index.html.erb
<h1>All Doctors</h1>

<ul>

  <% @patients.each do |patient| %>
    <li>
      <h3><%= link_to patient.full_name, patient_path(patient) %></h3>
      <h3><%= patient.email %></h3>
      <h3><%= patient.phone %></h3>
      <h3><%= patient.city %></h3>
      <h3><%= patient.age %></h3><hr>
    </li>
  <% end %>
</ul>

app/views/patients/show.html.erb
<div class="profile-container">
  <h1>Patient Profile</h1>

  <% if @patient.present? %>
    <div class="user-info">
      <p>
        <strong>ID:</strong>        <%= @patient.id %><br>
        <strong>Email:</strong>     <%= @patient.email %><br>
        <strong>Phone:</strong>     <%= @patient.phone %><br>
        <strong>Full Name:</strong> <%= @patient.full_name %><br>
        <strong>Age:</strong>       <%= @patient.age %><br>
        <strong>City:</strong>      <%= @patient.city %><br>
      </p><hr>
      <p>Total Closed Appointments: <%= @closed_appointments.size %></p><hr>

      <div class="profile-actions">
        <% if patient_signed_in? %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= link_to "My Appointments", appointments_path,  class:"btn btn-warning" %>
            <%= link_to 'Edit Profile', edit_patient_registration_path, class:"btn btn-primary me-md-2 button" %>
            <%= link_to 'Log out', destroy_patient_session_path, method: :delete, data: { turbo_method: :delete }, class:"btn btn-danger me-md-2 button"%>
          </div>
        <% end %>
      </div>
    </div>


    <div class="card">
      <div class="card-header">
        <h2 class="btn btn-success">Active Appointments: <%= @active_appointments.size  %></h2>
      </div>
      <div class="card-body">
        <% @active_appointments.each do |appointment| %>
          <p><strong>Appointment with <%= appointment.doctor.email %></strong></p>
          <p>Date: <%= appointment.date %></p>
          <p>Time: <%= appointment.time %></p>
          <p>Problem: <%= appointment.problem %></p>

          <% if appointment.recommendation.present? %>
            <p><strong>Recommendation:</strong> <%= appointment.recommendation.content %></p>
          <% end %>

          <%= link_to 'Close Appointment', close_appointment_path(appointment), method: :put, class: 'btn btn-danger', data: { turbo_method: :put } %>
        <% end %>
      </div>
    </div><br>

       <% else %>
         <p>User not found</p>
    <% end %>
</div>

app/views/recommendations/new.html.erb
<!-- app/views/recommendations/new.html.erb -->
<div class="container mt-4">
  <h1 class="mb-4">Add Recommendation</h1>

  <%= form_with(model: [@appointment, @recommendation], url: appointment_recommendations_path(@appointment), class: 'form') do |form| %>
    <div class="mb-3">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control', rows: 5 %>
    </div>

    <%= form.submit "Add Recommendation", class: 'btn btn-primary' %>
  <% end %>

  <%= link_to "Back to Appointment", appointment_path(@appointment), class: 'btn btn-secondary mt-3' %>
</div>