config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :patient
  devise_for :doctors

  resources :patients, only: [:index, :show]
  resources :doctors, only: [:index, :show] do
    resources :appointments, only: [:new, :create, :show]
  end

  root to: "home#index"

  resources :appointments do
    collection do
      get :closed_appointments
    end

    member do
      put :close
    end

    resources :recommendations, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :recommendation

  scope :closed, -> { where(status: 'closed') }


end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, uniqueness: true

  has_many :doctors

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["doctors"]
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :category
  has_many :appointments

  validates :email, :phone, :full_name, :age, :city, presence: true
  validates :phone, uniqueness: true

  def email_required?
   false
  end

  def email_changed?
   false
  end
  def self.ransackable_attributes(auth_object = nil)
    ["age", "categor_id", "category_id", "city", "created_at", "email", "encrypted_password", "full_name", "id", "phone", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end


end

app/models/patient.rb
class Patient < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments

  validates :email, :phone, :full_name, :age, :city, presence: true
  validates :phone, uniqueness: true

  def email_required?
   false
  end

  def email_changed?
   false
  end

  def self.ransackable_attributes(auth_object = nil)
    ["age", "city", "created_at", "email", "encrypted_password", "full_name", "id", "phone", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :appointment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :full_name, :phone, :age, :city, :category_id, :password, :password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @categories = Category.all
    category_id = params[:category_id]

    if category_id.present?
      @doctors = Doctor.where(category_id: category_id)
    else
      @doctors = Doctor.all
    end
  end

  def show
    @doctor = Doctor.find(params[:id])
    @appointments = @doctor.appointments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def show; end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = current_patient
    @active_appointments = current_patient.appointments.where(status: 'open')
    @closed_appointments = current_patient.appointments.where(status: 'closed')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "Clinic", root_path, class:"nav-link px-2 text-white" %></li>
        <%# <li><%= link_to "All Patients", patients_path , class:"nav-link px-2 text-white" %></li> 
        <li><%= link_to "All Doctors",  doctors_path ,class:"nav-link px-2 text-white" %></li>
      </ul>

      <%= link_to 'Мій профіль', doctor_path(current_doctor), class:"nav-link  my-nav-item" if doctor_signed_in? %>
      <%= link_to 'Мій профіль', patient_path(current_patient), class:"nav-link  my-nav-item"if patient_signed_in? %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TewDeviseCorect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>

    <div class=container>
      <%= yield %>
    </div>

  </body>
</html>